config/routes.rb
Device::Application.routes.draw do
  resources :codings
  root :to => 'home#index'
end

app/models/coding.rb
class Coding < ActiveRecord::Base
  attr_accessible :client, :device, :encode_mode, :rom_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/codings_controller.rb
class CodingsController < ApplicationController
  # GET /codings
  # GET /codings.json
  def index
    @codings = Coding.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @codings }
    end
  end

  # GET /codings/1
  # GET /codings/1.json
  def show
    @coding = Coding.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @coding }
    end
  end

  # GET /codings/new
  # GET /codings/new.json
  def new
    @coding = Coding.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @coding }
    end
  end

  # GET /codings/1/edit
  def edit
    @coding = Coding.find(params[:id])
  end

  # POST /codings
  # POST /codings.json
  def create
    @coding = Coding.new(params[:coding])

    respond_to do |format|
      if @coding.save
        format.html { redirect_to @coding, notice: 'Coding was successfully created.' }
        format.json { render json: @coding, status: :created, location: @coding }
      else
        format.html { render action: "new" }
        format.json { render json: @coding.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /codings/1
  # PUT /codings/1.json
  def update
    @coding = Coding.find(params[:id])

    respond_to do |format|
      if @coding.update_attributes(params[:coding])
        format.html { redirect_to @coding, notice: 'Coding was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @coding.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /codings/1
  # DELETE /codings/1.json
  def destroy
    @coding = Coding.find(params[:id])
    @coding.destroy

    respond_to do |format|
      format.html { redirect_to codings_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/codings_helper.rb
module CodingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/codings/_form.html.erb
<%= form_for(@coding) do |f| %>
  <% if @coding.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coding.errors.count, "error") %> prohibited this coding from being saved:</h2>

      <ul>
      <% @coding.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :device %><br />
    <%= f.text_field :device %>
  </div>
  <div class="field">
    <%= f.label :rom_id %><br />
    <%= f.text_field :rom_id %>
  </div>
  <div class="field">
    <%= f.label :client %><br />
    <%= f.select :client, [["Android", "ANDROID"], ["Iphone", "IPHONE"]] %>
  </div>
  <div class="field">
    <%= f.label :encode_mode %><br />
    <%= f.number_field :encode_mode %>
  </div>
  <div class="actions">
    <%= f.submit  "Submit", :class => "btn btn-primary"  %>
  </div>
<% end %>

app/views/codings/edit.html.erb
<h1>Editing coding</h1>

<%= render 'form' %>

<%= link_to 'Show', @coding %> |
<%= link_to 'Back', codings_path %>

app/views/codings/index.html.erb
<h1>Listing codings</h1>

<table>
  <tr>
    <th>Device</th>
    <th>Rom</th>
    <th>Client</th>
    <th>Encode mode</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @codings.each do |coding| %>
  <tr>
    <td><%= coding.device %></td>
    <td><%= coding.rom_id %></td>
    <td><%= coding.client %></td>
    <td><%= coding.encode_mode %></td>
    <td><%= link_to 'Show', coding %></td>
    <td><%= link_to 'Edit', edit_coding_path(coding) %></td>
    <td><%= link_to 'Destroy', coding, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Coding', new_coding_path %>

app/views/codings/new.html.erb
<h1>New coding</h1>

<%= render 'form' %>

<%= link_to 'Back', codings_path %>

app/views/codings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Device:</b>
  <%= @coding.device %>
</p>

<p>
  <b>Rom:</b>
  <%= @coding.rom_id %>
</p>

<p>
  <b>Client:</b>
  <%= @coding.client %>
</p>

<p>
  <b>Encode mode:</b>
  <%= @coding.encode_mode %>
</p>


<%= link_to 'Edit', edit_coding_path(@coding) %> |
<%= link_to 'Back', codings_path %>

app/views/home/index.html.erb
<h1>Device Record</h1>
<p>
用于手机视频编解码的数据记录，提示手机使用 硬编码 或者 软编码
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "RestPrev" %></title>
    <link href="/assets/favicon.ico" rel="shortcut icon">
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <style type="text/css">
      body { padding: 65px 0;}
    </style>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">RestPrev</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
              <%= yield %>
            </div>
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Sidebar</h3>
                <ul class="nav nav-list">
                  <li class="nav-header">Sidebar</li>
                  <li><%= link_to "Link1", "/path1"  %></li>
                  <li><%= link_to "Link2", "/path2"  %></li>
                  <li><%= link_to "Link3", "/path3"  %></li>
                </ul>
              </div><!--/.well -->
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>© Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>